// react/src/components/TablePagination.tsx
import React from 'react';
import type { PaginationLinks, PaginationMeta } from '@/types';

interface TablePaginationProps {
    links: PaginationLinks;
    meta: PaginationMeta;
    onPageChange: (page: number) => void;
    isFetching?: boolean;
    classNames: {
        pagination: string;
        paginationButton: string;
        paginationInfo: string;
    };
}

export function TablePagination({ links, meta, onPageChange, isFetching, classNames }: TablePaginationProps) {
    const hasPrevious = links.prev !== null;
    const hasNext = links.next !== null;

    // Build info text
    let infoText: string;
    if (meta.from !== null && meta.to !== null) {
        if (meta.total !== undefined) {
            infoText = `Showing ${meta.from} to ${meta.to} of ${meta.total} results`;
        } else {
            infoText = `Showing ${meta.from} to ${meta.to} results`;
        }
    } else {
        infoText = 'No results';
    }

    return (
        <nav className={classNames.pagination} aria-label="Table pagination">
            <span className={classNames.paginationInfo}>{infoText}</span>

            <div className="flex items-center gap-2">
                {links.first !== null && (
                    <button
                        type="button"
                        onClick={() => onPageChange(1)}
                        disabled={!hasPrevious || isFetching}
                        className={classNames.paginationButton}
                        aria-label="Go to first page"
                    >
                        First
                    </button>
                )}

                <button
                    type="button"
                    onClick={() => onPageChange(meta.current_page - 1)}
                    disabled={!hasPrevious || isFetching}
                    className={classNames.paginationButton}
                    aria-label="Go to previous page"
                >
                    Previous
                </button>

                <button
                    type="button"
                    onClick={() => onPageChange(meta.current_page + 1)}
                    disabled={!hasNext || isFetching}
                    className={classNames.paginationButton}
                    aria-label="Go to next page"
                >
                    Next
                </button>

                {links.last !== null && meta.last_page !== undefined && (
                    <button
                        type="button"
                        onClick={() => onPageChange(meta.last_page!)}
                        disabled={!hasNext || isFetching}
                        className={classNames.paginationButton}
                        aria-label="Go to last page"
                    >
                        Last
                    </button>
                )}
            </div>
        </nav>
    );
}

// vue/src/components/TablePagination.vue
<template>
    <nav :class="classNames.pagination" aria-label="Table pagination">
        <span :class="classNames.paginationInfo">{{ infoText }}</span>

        <div class="flex items-center gap-2">
            <button
                v-if="links.first !== null"
                type="button"
                @click="onPageChange(1)"
                :disabled="!hasPrevious || isFetching"
                :class="classNames.paginationButton"
                aria-label="Go to first page"
            >
                First
            </button>

            <button
                type="button"
                @click="onPageChange(meta.current_page - 1)"
                :disabled="!hasPrevious || isFetching"
                :class="classNames.paginationButton"
                aria-label="Go to previous page"
            >
                Previous
            </button>

            <button
                type="button"
                @click="onPageChange(meta.current_page + 1)"
                :disabled="!hasNext || isFetching"
                :class="classNames.paginationButton"
                aria-label="Go to next page"
            >
                Next
            </button>

            <button
                v-if="links.last !== null && meta.last_page !== undefined"
                type="button"
                @click="onPageChange(meta.last_page!)"
                :disabled="!hasNext || isFetching"
                :class="classNames.paginationButton"
                aria-label="Go to last page"
            >
                Last
            </button>
        </div>
    </nav>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { PaginationLinks, PaginationMeta } from '@/types';

const props = defineProps<{
    links: PaginationLinks;
    meta: PaginationMeta;
    onPageChange: (page: number) => void;
    isFetching?: boolean;
    classNames: {
        pagination: string;
        paginationButton: string;
        paginationInfo: string;
    };
}>();

const hasPrevious = computed(() => props.links.prev !== null);
const hasNext = computed(() => props.links.next !== null);

const infoText = computed(() => {
    const { from, to } = props.meta;
    if (from !== null && to !== null) {
        if (props.meta.total !== undefined) {
            return `Showing ${from} to ${to} of ${props.meta.total} results`;
        }
        return `Showing ${from} to ${to} results`;
    }
    return 'No results';
});
</script>
