// react/src/cells/ComponentCell.tsx
import React from 'react';
import type { Row } from '@/types';
import { getCellComponent } from '@/registries/component-registry';

interface ComponentCellProps {
    componentName: string;
    row: Row;
    columnName: string;
}

export function ComponentCell({ componentName, row, columnName }: ComponentCellProps) {
    const Component = getCellComponent(componentName);

    if (!Component) {
        return null;
    }

    return <Component row={row} value={row[columnName]} column={columnName} />;
}

// vue/src/cells/ComponentCell.vue
<template>
    <component v-if="CellComp" :is="CellComp" :row="row" :value="row[columnName]" :column="columnName" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { Row } from '@/types';
import { getCellComponent } from '@/registries/component-registry';

const props = defineProps<{
    componentName: string;
    row: Row;
    columnName: string;
}>();

const CellComp = computed(() => getCellComponent(props.componentName));
</script>
