// vue/src/cells/DateCell.vue
<template>
    <span v-if="formattedValue == null" class="text-gray-400 dark:text-gray-500">-</span>
    <time v-else :datetime="rawValue ?? undefined" class="text-sm text-gray-600 dark:text-gray-400">
        {{ displayValue }}
    </time>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{
    formattedValue: string | null;
    rawValue?: string | null;
    local?: boolean;
    includeTime?: boolean;
}>();

const displayValue = computed(() => {
    if (props.formattedValue == null) return null;

    if (props.local && props.rawValue) {
        try {
            const date = new Date(props.rawValue);
            const options: Intl.DateTimeFormatOptions = props.includeTime
                ? { dateStyle: 'medium', timeStyle: 'short' }
                : { dateStyle: 'medium' };
            return new Intl.DateTimeFormat(undefined, options).format(date);
        } catch {
            return props.formattedValue;
        }
    }

    return props.formattedValue;
});
</script>

// react/src/cells/DateCell.tsx
import React from 'react';

interface DateCellProps {
    formattedValue: string | null;
    rawValue?: string | null;
    local?: boolean;
    includeTime?: boolean;
}

export function DateCell({ formattedValue, rawValue, local, includeTime }: DateCellProps) {
    if (formattedValue === null || formattedValue === undefined) {
        return <span className="text-gray-400 dark:text-gray-500">-</span>;
    }

    let displayText = formattedValue;

    if (local && rawValue) {
        try {
            const date = new Date(rawValue);
            displayText = includeTime
                ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(date)
                : new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(date);
        } catch {
            displayText = formattedValue;
        }
    }

    return (
        <time dateTime={rawValue ?? undefined} className="text-sm text-gray-600 dark:text-gray-400">
            {displayText}
        </time>
    );
}
